[theme]
base = "light"
primaryColor = "#1f77b4"
backgroundColor = "#f8f9fb"
secondaryBackgroundColor = "#eef1f5"
textColor = "#262730"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
